### PR TITLE
Add the Gentoo Linux guide

### PR DESCRIPTION
**Pull request by raycasted**
Your Gentoo guide was very good, thank you!

I hope your website becomes successful!

I wrote an article about the Gentoo guide because I really wanted to see that as a website.

### CODE REVIEW

**Comment by raycasted** [comment]
I am currently verifying if the article works well

**Comment by raycasted** [comment]
Finished verifying, guide works well.

**Comment by arthurmelton** [comment]
To me this looks like its pretty much just the audio rip from the video, and I think that just makes it sound really weird for a website guide.

> In this case I have 10GB of RAM and five CPU threads. So I will use the -j5 and -l5 options.

This is an example of what I mean. In the video it makes sense to word it like this, but in a guide it sounds weird to say "In this case". You also skip over the fact of why 10GB of Ram and 5 CPU threads makes you pick `-j5 -l5`, others might think its just a number you get a feeling for.

I think its a good starting place, but I think some of the wording might need to change to make it fit a text guide more.

**Comment by AleDenshi** [comment]
Great guide! As @arthurmelton says it might need some cleanup in some places, just to make the tone more appropriate. I'll merge it in the meantime as a draft.

**Comment by raycasted** [comment]
@arthurmelton I agree, I just wanted to make a draft for people to add on top of it (I am not an expert in explaining stuff)

**Pull request merged**
