### PR TITLE
Updated css for better readablity and comfort

### PR DESCRIPTION
**Pull request by AnAverageBeing**
The site has very hard colors which were not comfortable to read.

Changed colors and fonts to be more readable and comfy.

increased line-height.

Changed fonts.

### CODE REVIEW

**Comment by AleDenshi** [comment]
I appreciate the effort, but I think the simple look of the website is part of the self-hosting charm. I might look into fixing some of the spacing and the colors though, thanks for those suggestions.

**Comment by AnAverageBeing** [comment]
> I appreciate the effort, but I think the simple look of the website is part of the self-hosting charm. I might look into fixing some of the spacing and the colors though, thanks for those suggestions.

can u please increase the line height and fix the colors of syntax because some people(like me) have eye problems and increasing line height helps them read better and also when reading comments in that syntax highlighting is hard if u can please consider this it would be a great help.

**Comment by zacoons** [comment]
Try using a blue light filter on you PC, it actually makes the site a bit softer. There's one built into Windows, just look for "Night light" in system settings.

**Comment by AnAverageBeing** [comment]
> Try using a blue light filter on your PC, it actually makes the site a bit softer. There's one built into Windows, just look for "Night light" in system settings.

no no thats not the issue i have night light on my kde setup but it dont help the thing is proper spacing for me even with lenses and stuff i get the ghosting effect when i see so when there is less space between lines the images from lines on top overlaps with bottom line so it makes it hard to read so increasing line height helps a lot but thanks for your suggestion

**Pull request closed without merging**
